config/routes.rb
Questso::Application.routes.draw do

  devise_for :users
  resources :posts
  put 'posts/:id/upvote', to: 'posts#upvote', constraints: {id: /\d+/}
  put 'posts/:id/downvote', to: 'posts#downvote', constraints: {id: /\d+/}

  [:latest, :hot, :favorited, :read, :posted, :unread, :new, :trending, :fresh].each do |filter|
    get "#{filter}" => "list##{filter}"
    get "#{filter}/more" => "list##{filter}"
  end

  [:latest, :hot, :favorited, :read, :posted, :unread, :new, :trending, :fresh].each do |filter|
    root to: "list##{filter}", :as => "list_#{filter}"
  end

  match "/signup", to: "users#signup", via: "get"
  match "/signin", to: "users#signin", via: "get"

  match "/close", to: "static#close", via: "get"

  resources :users

  root to: "list#latest"

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_attached_file :photo, :styles => { :medium => ["570", :png], :thumb => ["400x400>", :png] }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	attr_accessor :login
	
	has_many :posts

	validates_presence_of :username
	validates :username,
		:uniqueness => {
		  :case_sensitive => false
		}

	def self.find_first_by_auth_conditions(warden_conditions)
	  conditions = warden_conditions.dup
	  if login = conditions.delete(:login)
	    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
	  else
	    where(conditions).first
	  end
	end	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController

  [:latest, :hot, :favorited, :read, :posted, :unread, :new, :trending, :fresh].each do |filter|
    define_method(filter) do
      list = Post.all.reverse
      @filter = filter
      respond(list)
    end
  end

  def respond(list)
  	@posts = list
    flash.now[:alert] = "test message"
    render 'list'
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	respond_to :html,:json

	def new
	end

	def create
		@post = Post.create(params.require(:post).permit(:photo, :title, :description))
		@post.save
		respond_with @post
	end

	def show
		@post = Post.find_by(:id=>[params[:id]])
		respond_with @post
	end

  def upvote
    puts params[:id]
    @post = Post.find_by(:id=>[params[:id]])
    @post.increment! :vote_count
    respond_to do |format|
      format.json { render :json => @post }
    end
  end

  def downvote
    @post = Post.find_by(:id=>[params[:id]])
    if @post.vote_count > 0
      @post.decrement! :vote_count
    end
    respond_to do |format|
      format.json { render :json => @post }
    end
  end

  def destroy
    @post = Post.find_by(:id=>[params[:id]])
    @post.destroy
    respond_with @post
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

	# close popup dialog, when redirect from facebook
	def close
		render
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	
	def signup
		@user = User.new
		
	end

	def signin
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# return abosolute url for a post's photo
	def post_photo_url(photo, style = :medium)
		"#{request.protocol}#{request.host_with_port}#{photo.url(style)}"
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= content_for?(:title) ? yield(:title) : 'Trenvenue' %></title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>

	<%= yield :head %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
     m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
     })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

     ga('create', 'UA-45319639-1', 'trenvenue.com');
     ga('require', 'displayfeatures');
     ga('send', 'pageview');
  </script>

  <!-- start Mixpanel -->
  <script type="text/javascript">
    (function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);
    b._i.push([a,e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);
    mixpanel.init("bcc72755a7a2080616c833019a9cba1a");
  </script>
  <!-- end Mixpanel -->

</head>
<body>
	
	<div class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="row">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand main-logo" href="/">
						<%= image_tag "logo.png", :alt => "Trenvenue", :title => "Trenvenue"%>
					</a>
				</div>			
          <div class="navbar-right">
            <div style="margin: 20px 15px 0 0;">
            <% if user_signed_in? %>
                <% if current_user.try(:admin?) %>
                	<a data-toggle="modal" href="#uploadModal" class="btn btn-danger">Upload</a>
                <% end %>
                <%= link_to('Sign Out', destroy_user_session_path, :method => :delete, :class => 'btn btn-default') %>
            <% else %>
                <%= link_to("Join Us", new_user_registration_path, :class => 'btn btn-success') %>
                <%= link_to('Sign In', new_user_session_path, :class => 'btn btn-default')  %>
            <% end %>
            </div>
          </div>
				<!--  TODO: comment out navigation for now. until find better way to do it
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<%= active_link_to 'Hot', hot_path, :wrap_tag => :li %>
						<%= active_link_to 'Trending', trending_path, :wrap_tag => :li %>
						<%= active_link_to 'Fresh', fresh_path, :wrap_tag => :li %>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">More <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li class="dropdown-header">Nav header</li>
								<li><a href="#">Separated link</a></li>
								<li><a href="#">One more separated link</a></li>
							</ul>
						</li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li>
							<div>
								<a data-toggle="modal" href="#uploadModal" class="btn btn-danger">Upload</a>
							</div>
						</li>
					</ul>
				</div>
				-->					
			</div>
		</div>
	</div>
	<div class=" afternav">
		<div class="container ">

			<div class="left-block">
			</div>

			<!-- Ads Placeholder, Site social Placeholder -->
			<div class="right-block">	
			<!-- <a class="btn btn-default"><i class="icon-gear icon-2x"></i>	</a> -->
					        	
			</div>
		</div>
	</div>

	<div class="container main-container" >
	  <%= yield %>
	</div>

	<!-- Login Modal -->
	<div class="modal" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Upload a Photo</h4>
				</div>
				<div class="modal-body">
					<%= form_for Post.new, :url => posts_path, :html => { :multipart => true } do |form|%>
						<div class="form-group">
							<%= form.label(:photo) %>
							<%= form.file_field(:photo) %>
						</div>
						<div class="form-group">
							<%= form.label(:title)%>
							<%= form.text_field(:title, :class => "form-control")%>
						</div>
						<div class="form-group">
							<%= form.label(:description)%><span class="help-block pull-right">(Optional)</span>
							<%= form.text_area(:description, :class => "form-control")%>
						</div>
						<%= submit_tag("Submit", class: "btn btn-primary") %>
					<% end %>
				</div>
<!-- 				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-primary">Save changes</button>
				</div> -->
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->

</body>
</html>

app/views/list/_post.html.erb
<div class="row post-container">
	<article>
		<header class="post-header">
			<h2 class="post-title">
				<%= link_to post.title, post_path(post.id)%>
			</h2>

			<div class="post-vote">
				<div class="post-action-list">
					<div class="post-action">
						<ul class="list-unstyled">
							<li>
								<a href="javascript:void(0)" >
									<i class="icon-thumbs-up-alt icon-2x icon-upvote" data-id="<%= post.id %>"></i>
								</a>
							</li>
							<li>
								<a href="javascript:void(0)">
									<span class="vote-counter vote-counter-<%= post.id %>"><%= post.vote_count %></span>
								</a>
							</li>
							<li>
								<a href="javascript:void(0)" >
									<i class="icon-thumbs-down-alt icon-2x icon-downvote" data-id="<%= post.id %>"></i>
								</a>
							</li>
						</ul>
					</div>
					<div class="post-action">
						<!-- comment -->
					</div>
				</div>
			</div>
		</header>

		<div class="row">
			<div class="col-md-10" style="max-width:80%">
        <a href="<%= post_path(post.id) %>">
          <%= image_tag post.photo.url(:medium), :class => "img-rounded"%>
        </a>
			</div>
		</div>

		<div class="row">
			<div class="col-md-10 share" style="border: none;">
				<div class="share-count">
					<p><strong>999</strong> shares</p> 
				</div>

				<ul class="list-unstyled">
					<li><a class="facebook facebook-share" href="javascript:void(0)" 
					       data-url="<%= post_url(post) %>"></a></li>
					<li><a class="twitter" href="javascript:void(0)"></a></li>
					<li><a class="google-plus" href="javascript:void(0)"></a></li>
					<li><a class="pinterest" href="javascript:void(0)"></a></li>
					<li><a class="email" href="javascript:void(0)"></a></li>
				</ul>
			</div>
		</div>	
	</article>
</div>

app/views/list/list.html.erb
<div class="row">
	<div id="post-collection" class="col-md-8" style="min-height: 1000px;">
			
		<%= render collection: @posts, partial: "post" %>

		<script type="text/template" id="post-template">
			<div class="row post-container">
				<article>
					<header class="post-header">
						<h2 class="post-title">
							<a href="#" >{{ title }}</a>
						</h2>

						<div class="post-vote">
							<div class="post-action-list">
								<div class="post-action">
									<ul class="list-unstyled">
										<li>
											<a href="javascript:void(0)" >
												<i class="icon-thumbs-up-alt icon-2x"></i>
											</a>
										</li>
										<li>
											<a href="javascript:void(0)">
												<span class="vote-counter">7777</span>
											</a>
										</li>
										<li>
											<a href="javascript:void(0)" >
												<i class="icon-thumbs-down-alt icon-2x"></i>
											</a>
										</li>
									</ul>
								</div>
								<div class="post-action">
									<!-- comment -->
								</div>
							</div>
						</div>
					</header>

					<div class="row">
						<div class="col-md-10" style="max-width:80%">
							{{ image_url }}							
						</div>
					</div>

					<div class="row">
						<div class="col-md-10 share" style="border: none;">
							<div class="share-count">
								<p><strong>999</strong> shares</p> 
							</div>

							<ul class="list-unstyled">
								<li><a class="facebook" href="javascript:void(0)"></a></li>
								<li><a class="twitter" href="javascript:void(0)"></a></li>
								<li><a class="google-plus" href="javascript:void(0)"></a></li>
								<li><a class="pinterest" href="javascript:void(0)"></a></li>
								<li><a class="email" href="javascript:void(0)"></a></li>
							</ul>
						</div>
					</div>	
				</article>
			</div>
		</script>

	</div>

	<div class="col-md-4" style="margin-top: 20px; min-height: 1000px;">
		<!-- Right-hand column -->
		<!-- Ads columns, relavent posts-->

  <div id="thumb-collection">

    <%= render collection: @posts, partial: "thumb" %>

  </div>

	</div>
</div>

app/views/posts/_ad.html.erb
<article class="thumb-container">

	<a class="thumb-link" href="/">
		<span class="img-rounded thumb-img" style="background-image: url(<%= thumb.photo.url(:thumb) %>)">&nbsp;</span>

		<p><%= thumb.title %></p>
	</a>

</article>

app/views/posts/_thumb.html.erb
<article class="thumb-container">

	<a class="thumb-link" href="/">
		<span class="img-rounded thumb-img" style="background-image: url(<%= thumb.photo.url(:thumb) %>)">&nbsp;</span>

		<p><%= thumb.title %></p>
	</a>

</article>

app/views/posts/new.html.erb
<div class="row">
	<div id="post-collection" class="col-md-8" style="min-height: 1000px;">
		<div class="row post-container">
			<article>
				<header class="post-header">
					<h2 class="post-title">
						<a href="#" ><%= @post.title %></a>
					</h2>

					<div class="post-vote">
						<div class="post-action-list">
							<div class="post-action">
								<ul class="list-unstyled">
									<li>
										<a href="javascript:void(0)" >
											<i class="icon-thumbs-up-alt icon-2x"></i>
										</a>
									</li>
									<li>
										<a href="javascript:void(0)">
											<span class="vote-counter">7777</span>
										</a>
									</li>
									<li>
										<a href="javascript:void(0)" >
											<i class="icon-thumbs-down-alt icon-2x"></i>
										</a>
									</li>
								</ul>
							</div>
							<div class="post-action">
								<!-- comment -->
							</div>
						</div>
					</div>
				</header>

				<div class="row">
					<div class="col-md-10" style="max-width:80%">
						<%= image_tag @post.photo.url(:medium), :class => "img-rounded"%>
					</div>
				</div>

				<div class="row">
					<div class="col-md-10 share" style="border: none;">
						<div class="share-count">
							<p><strong>999</strong> shares</p> 
						</div>

						<ul class="list-unstyled">
							<li><a class="facebook" href="javascript:void(0)"></a></li>
							<li><a class="twitter" href="javascript:void(0)"></a></li>
							<li><a class="google-plus" href="javascript:void(0)"></a></li>
							<li><a class="pinterest" href="javascript:void(0)"></a></li>
							<li><a class="email" href="javascript:void(0)"></a></li>
						</ul>
					</div>
				</div>	
			</article>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<% content_for :head do %>

	<meta property="og:title" content="<%= @post.title %>"></meta>
	<meta property="og:description" content="<%= @post.description %>"></meta>
	<meta property="og:image" content="<%= post_photo_url(@post.photo) %>"></meta>
	<meta property="fb:app_id" content="471240789685989"></meta>
<% end %>


<div class="row">
	<div id="post-collection" class="col-md-8" style="min-height: 1000px;">
		<div class="row post-container">
			<article>
				<header class="post-header">
					<h2 class="post-title">
						<a href="#" ><%= @post.title %></a>
					</h2>

					<div class="post-vote">
						<div class="post-action-list">
							<div class="post-action">
								<ul class="list-unstyled">
									<li>
										<a href="javascript:void(0)" >
											<i class="icon-thumbs-up-alt icon-2x icon-upvote" data-id="<%= @post.id %>"></i>
										</a>
									</li>
									<li>
										<a href="javascript:void(0)">
											<span class="vote-counter vote-counter-<%= @post.id %>"><%= @post.vote_count %></span>
										</a>
									</li>
									<li>
										<a href="javascript:void(0)" >
											<i class="icon-thumbs-down-alt icon-2x icon-downvote" data-id="<%= @post.id %>"></i>
										</a>
									</li>
								</ul>
							</div>
							<div class="post-action">
								<!-- comment -->
							</div>
						</div>
					</div>
				</header>

				<div class="row">
					<div class="col-md-10" style="max-width:80%">
						<%= image_tag @post.photo.url(:medium), :class => "img-rounded"%>
					</div>
				</div>

				<div class="row">
					<div class="col-md-10 share" style="border: none;">
						<div class="share-count">
							<p><strong>999</strong> shares</p> 
						</div>

						<ul class="list-unstyled">
							<li><a class="facebook facebook-share" href="javascript:void(0)"
							       data-url="<%= post_url(@post) %>"></a></li>
							<li><a class="twitter" href="javascript:void(0)"></a></li>
							<li><a class="google-plus" href="javascript:void(0)"></a></li>
							<li><a class="pinterest" href="javascript:void(0)"></a></li>
							<li><a class="email" href="javascript:void(0)"></a></li>
						</ul>

					</div>
            <% if user_signed_in? %>
              <div>
                <p><a class="btn btn-danger float-right icon-delete-post" data-id="<%= @post.id %>">Delete</a></p>
              </div>
            <% end %>
				</div>	
			</article>
		</div>
	</div>

	<div class="col-md-4" style="margin-top: 20px; min-height: 1000px;">
		<!-- Right-hand column -->
		<!-- Ads columns, relavent posts-->

    <div id="ads-collection">
      <%= render collection: @posts, partial: "ad" %>
    </div>

    <div id="thumb-collection">
      <%= render collection: @posts, partial: "thumb" %>
    </div>
	</div>

</div>

app/views/users/signin.html.erb
<% provide(:title, "Sign In")%>

<div class="container">
	<form class="form-signin span4">
		<h2 class="form-signin-heading">Please sign in</h2>
		<input type="text" class="form-control" placeholder="Email address" required autofocus>
		<input type="password" class="form-control" placeholder="Password" required>
		<label class="checkbox">
			<input type="checkbox" value="remember-me"> Remember me
		</label>
		<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
	</form>
</div>

app/views/users/signup.html.erb
<% provide(:title, "Sign Up")%>

<div class="container">
	<form class="form-signup span4">
		<h2 class="form-signup-heading">Please sign up</h2>
		<input type="text" class="form-control" placeholder="Email address" required autofocus>
		<input type="password" class="form-control" placeholder="Password" required>
		<input type="password" class="form-control" placeholder="Confirmed Password" required>
		<button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
	</form>
</div>

	